// <auto-generated />
namespace SSCS_LIVE_MVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NewMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201311140401106_NewMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
